version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: recipe_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
